### ISSUE TITLE
paging for gravsearch

### ISSUE THREAD

**Issue by janCstoffregen** [dasch-swiss/0829-kwa-app#17]
when you scroll down, the next page is loaded automatically.

@mattssp I need the info, what needs to be included in the gravsearch query so that the next page is loaded

**Comment by mattssp** [comment]
You can simply add the line

OFFSET 0

to the end of the query (or OFFSET 1 for the second page).
As long as result[knora-api:mayHaveMoreResults] is true, you can request an other page.
You can also send the query to the v2/searchextended/count route to get the number of resources.

**Comment by janCstoffregen** [comment]
thanks, it's working
