### ISSUE TITLE
Which gitflow

### ISSUE THREAD

**Issue by janCstoffregen** [dasch-swiss/0829-kwa-app#7]
Hi guys, how are you? I started the design documentation, but it's wip, please have a look after Wednesday evening, it is not ordered at all yet, I'll improve it until our meeting on Thursday. https://github.com/dasch-swiss/0829-kwa-app/tree/master/docs/design%20specification/1.%20phase%20-%20findbuch

I'd like to ask about your preferred gitflow, should pull requests be merged in devel and the master branch only updated when there is a first stable version, or how would you like to proceed?

Thanks and best regards,
Jan

@mattssp zur info

**Comment by subotic** [comment]
@janCstoffregen I think that you can merge directly into `master`. In my opinion, each PR should be self-contained and result in a working app.

**Comment by janCstoffregen** [comment]
ok, I will do it in this way then, thank you!
